[tool.poetry]
name = "fileorganizer"
version = "0.1.0"
description = ""
authors = ["wendrew"]

[tool.poetry.dependencies]
python = "^3.9"
Flask = "^1.1.2"
schedule = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
